version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/c-cmake"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/cpp-cmake"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/crystal"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/dotnet"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/golang"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/java"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/julia"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/nodejs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/raku"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/rust"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/swift"
    schedule:
      interval: "weekly"
