name: Run Tests
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run builds and test output
      run: ./run_tests.sh